spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: false
        ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug
auth:
  jwt:
    issuer: team.sparta.com
    secret: c5t6gzuXneIM3d0Eafy2F3MrkK41BUfD
    accessTokenExpirationHour: 168

